#!/usr/bin/env python

# Copyright 2009-2013 INRIA Rhone-Alpes, Service Experimentation et
# Developpement
# This file is part of Execo, released under the GNU Lesser Public
# License, version 3 or later.

import sys, os, optparse, subprocess

if __name__ == "__main__":

    progname = os.path.basename(sys.argv[0])

    usage = """usage: %s <engine> [options] <arguments>

instanciate <engine> from python module <engine>.py and call method
start() on it.

if <engine> is of the form <engine_module_name:engine_class_name> then
instanciate <engine_class_name> from python module
<engine_module_name>""" % (progname, ", ".join(additional_search_pathes))

    if len(sys.argv) < 2:
        print "ERROR: missing argument"
        print usage,
        exit(1)

    module_name, _, class_name = sys.argv[1].partition(":")
    del sys.argv[1]
    if not class_name: class_name = module_name
    engine_module = __import__(module_name)
    engine_class = getattr(engine_module, class_name)
    engine_instance = engine_class()
    engine_instance.start()
