#!/usr/bin/env python
# -*- coding: utf-8 -*-

import execo

actions = [ execo.Local("ls -al ~"),
            execo.Local("false"),
            execo.Local("/dev/null"),
            execo.Local("echo begin ; sleep 2 ; echo end"),
            execo.Local("ping -c 2 localhost") ]

map(execo.Local.start, actions)
map(execo.Local.wait, actions)

actions += [ execo.Local("uname -a") ]

print execo.Report(actions).output()
