#!/usr/bin/env python

import sys, os, shutil, pickle
from os.path import join as pjoin
import execo, execo_g5k, execo_engine

# usage: convert-paramsweeper-format <paramsweeper_dir>

ps_dir = sys.argv[1]

done_path = os.path.join(ps_dir, "done")

print "backup copy of %s to %s.bak" % (done_path, done_path)
shutil.copy(done_path, done_path + ".bak")
print "opening %s" % (done_path,)
with open(done_path, "a+") as done_file:
    print "reading done parameters"
    done = pickle.load(done_file)
    print "read %s done parameters" % (len(done),)
    print "writing done parameters in new format"
    done_file.truncate(0)
    for p in done:
        pickle.dump(p, done_file)
    print "wrote %s done parameters" % (len(done),)
print "finished"
