#!/usr/bin/env python

from execo import Local, Report
actions = [ Local("ls -al ~"),
            Local("false"),
            Local("/dev/null"),
            Local("portinouak"),
            Local("echo begin ; sleep 2 ; echo end"),
            Local("ping -c 2 localhost") ]
[ action.start() for action in actions ]
[ action.wait() for action in actions ]
actions.append(Local("uname -a"))
print Report(actions).output()
